import { pageMetadata } from "@/lib/seo";
import { photo } from "@/data/image-library";
import { consultingPackages, consultingRates, coordinationOffer } from "@/data/consulting";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown } from "lucide-react";

import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { ButtonLink } from "@/components/ui/button-link";

export const metadata: Metadata = pageMetadata({ title: "Consulting and site assessments", description: "Compare GreenSprout consultations, site assessments, Bronze, Silver and Gold packages, project coordination and technical service fees in Kenya.", path: "/consulting" });

const startingPoints = [
  { number: "01", title: "Talk it through", price: consultingRates[0].price, copy: "A scheduled 30–45 minute phone or online session for early advice and a practical next step.", detail: "A first enquiry is welcome. The paid session is for advice tailored to your site; it does not include a visit or written technical report.", image: photo.soilSample, href: "/quote?service=consultation" },
  { number: "02", title: "Walk the site", price: consultingRates[1].price, copy: "We visit the land to consider its terrain, slope, vegetation, erosion risks and proposed use.", detail: "A detailed site survey starts from KSh 25,000. Travel, laboratory testing and the agreed deliverables are clarified before booking.", image: photo.siteAssessment, href: "/quote?service=site-assessment" },
];
const rateGroups = ["Advice & assessment", "Planning & documents", "Delivery & follow-up"] as const;

export default function ConsultingPage() {
  return <><SiteHeader /><main>
    <section className="p5-hero"><Image src={photo.siteAssessment} alt="A specialist assessing land conditions" fill priority sizes="100vw" /><div className="p5-hero-shade"/><div className="page-shell p5-hero-content"><p className="eyebrow light">GreenSprout consulting</p><h1>Site consulting and project support.</h1><p>Start with one question, a site visit or a complete plan. We explain the work, the fee and the next step before you commit.</p><div className="p5-actions"><ButtonLink href="/quote" label="Tell us about your site" variant="light" /><Link href="#ways-to-start" className="p5-text-link">Explore the options <ArrowRight size={18}/></Link></div></div></section>

    <section className="p5-consult-story"><div className="page-shell p5-consult-story-grid"><div className="p5-consult-story-image"><Image src={photo.soilSample} alt="Soil and ground conditions examined during planning" fill sizes="(max-width:900px) 100vw, 48vw"/></div><div className="p5-consult-story-copy"><p className="eyebrow">One project, a clear path</p><h2>Consultation, survey or project plan.</h2><p>Sometimes one focused conversation is enough. Other sites need a visit, soil information, specifications or someone to coordinate the work.</p><p>Every paid assignment has a written scope, deliverables and any separate expenses agreed first.</p><Link href="#ways-to-start">Find your starting point <ArrowRight size={18}/></Link></div></div></section>

    <section id="ways-to-start" className="p12-start page-shell"><div className="p5-section-heading"><p className="eyebrow">First steps</p><h2>Choose a consultation or site survey.</h2></div><div className="p12-start-grid">{startingPoints.map(item=><article key={item.number} className="p12-start-card"><div className="p12-start-image"><Image src={item.image} alt="" fill sizes="(max-width:680px) 100vw, 50vw"/></div><div className="p12-start-copy"><span>{item.number} / FIRST STEP</span><h3>{item.title}</h3><strong>{item.price}</strong><p>{item.copy}</p><small>{item.detail}</small><Link href={item.href}>Enquire about this service <ArrowRight size={18}/></Link></div></article>)}</div></section>

    <section className="p5-image-band"><Image src={photo.projectPlanning} alt="A project plan and landscape drawings being prepared" fill sizes="100vw"/><div className="p5-image-band-shade"/><div className="page-shell"><p className="eyebrow light">From advice to a plan</p><h2>Site planning before implementation.</h2></div></section>

    <section id="packages" className="p5-packages page-shell"><div className="p5-centered"><p className="eyebrow">Consulting packages</p><h2>Bronze, Silver and Gold consulting packages.</h2><p>These are starting scopes. Your written proposal confirms the number of visits, duration, deliverables and any extra expenses.</p></div><div className="p5-package-grid p12-package-grid">{consultingPackages.map((item,i)=><article id={item.slug} className={i===1?"p5-package p5-package-accent p12-package":"p5-package p12-package"} key={item.name}><div className="p12-package-image"><Image src={item.image} alt="" fill sizes="(max-width:680px) 100vw, 33vw"/></div><div className="p12-package-body"><span>0{i+1} / {item.name}</span><h3>{item.name}</h3><strong>{item.price}</strong><p className="p5-audience">{item.audience}</p><p>{item.description}</p><ul className="p12-highlights">{item.highlights.map(point=><li key={point}><Check size={17}/>{point}</li>)}</ul><details className="p12-package-details"><summary>See everything included <ChevronDown size={18}/></summary><ul>{item.inclusions.map(point=><li key={point}><Check size={17}/>{point}</li>)}</ul></details><Link href={`/quote?service=${item.slug}`}>Discuss {item.name} <ArrowRight size={18}/></Link></div></article>)}</div><p className="p5-package-note">Package fees cover the agreed consulting work. Materials, installation, laboratory charges, travel and third-party services are identified separately where applicable.</p></section>

    <section id="coordination" className="p5-delivery"><div className="page-shell p5-delivery-grid"><div><p className="eyebrow light">Project coordination</p><h2>Project coordination and supervision.</h2><p>We can connect suppliers, coordinate contractors and fabrication, monitor implementation and report on progress. Supervision, quality checks and handover can be included in a defined delivery scope.</p><ul className="p12-delivery-list"><li>People, suppliers and programme aligned</li><li>Important work stages inspected</li><li>Progress, risks and decisions reported</li><li>Final inspection and maintenance handover</li></ul><p className="p12-delivery-fee"><strong>{coordinationOffer.price}</strong> · The fee may be fixed or based on project value after the work is defined. Coordination already included in an approved package is not billed again.</p><ButtonLink href="/quote?service=project-coordination" label="Discuss project coordination" variant="light" /></div><div className="p5-delivery-image"><Image src={photo.projectCoordination} alt="Project team reviewing a site plan during implementation" fill sizes="(max-width:900px) 100vw, 45vw" /></div></div></section>

    <section id="individual-services" className="p12-rates"><div className="page-shell"><div className="p12-rates-heading"><div><p className="eyebrow">Focused support</p><h2>Individual consulting services</h2></div><p>Choose a stand-alone service instead of a package. These are starting rates; we confirm the output, timing, location and total fee in writing.</p></div><div className="p12-rates-layout"><div className="p12-rates-groups">{rateGroups.map(group=><div className="p12-rate-group" key={group}><h3>{group}</h3>{consultingRates.filter(item=>item.category===group).map(item=><Link href={`/quote?service=${item.value}`} className="p12-rate-row" key={item.value}><span><strong>{item.title}</strong><small>{item.detail}</small></span><span className="p12-rate-price">{item.price}<ArrowRight size={17}/></span></Link>)}</div>)}</div><div className="p12-rates-visual"><Image src={photo.qualityInspection} alt="A technical quality check on established ground" fill sizes="(max-width:900px) 100vw, 33vw"/><div><span>FROM FIRST VISIT TO HANDOVER</span><strong>Choose only the support your site needs.</strong></div></div></div><p className="p12-rate-note">Laboratory fees, transport, accommodation, materials and third-party work are separate where required. A package already covering a service will not be charged for that same service again.</p></div></section>

    <section className="p12-training"><div className="page-shell p12-training-grid"><div><p className="eyebrow">Training & workshops</p><h2>Training and workshops</h2><p>Practical sessions can be tailored for landscapers, youth groups, county teams, contractors and institutions. Current topics can include lawn care, traditional turf installation, site preparation and aftercare. Specialist hydroseeding training is planned for a later phase.</p><p className="p12-training-price">From KSh 100,000 <span>per workshop day</span></p><p>We agree the audience, learning goals, length, location and any travel or equipment needs in the quotation.</p><ButtonLink href="/quote?service=training" label="Plan a workshop" /></div><div className="p12-training-image"><Image src={photo.sodDetail} alt="Natural turf installation in progress" fill sizes="(max-width:900px) 100vw, 48vw"/></div></div></section>

    <section className="p5-closing"><Image src={photo.landRehabilitation} alt="Vegetation returning to a restored site" fill sizes="100vw"/><div className="p5-closing-shade"/><div className="page-shell"><p className="eyebrow light">Your next step</p><h2>Request a consulting quote.</h2><p>Share your location, approximate area and the outcome you need. We will recommend a suitable starting point and explain any paid scope before booking.</p><ButtonLink href="/quote" label="Get a quote" variant="light" /></div></section>
  </main><SiteFooter/></>;
}
